# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH_COMPDUMP=$ZSH/cache/zcompdump/.zcompdump-$HOST

export ZSH="$HOME/.oh-my-zsh"

source ~/.zplug/init.zsh

zplug "zplug/zplug", hook-build:'zplug --self-manage'
zplug 'Aloxaf/fzf-tab'
zplug "romkatv/powerlevel10k", as:theme, depth:1
zplug "plugins/git-extras", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "junegunn/fzf"
zplug 'wfxr/forgit'
zplug 'xPMo/zsh-ls-colors'
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "b4b4r07/enhancd", use:init.sh, defer:2
# zplug "MichaelAquilina/zsh-auto-notify"

if ! zplug check; then
    zplug install
fi

zplug load

source ~/.zplug/repos/b4b4r07/enhancd/init.sh
ENHANCD_DIR=$HOME/.zplug/repos/b4b4r07/enhancd/
ENHANCD_FILTER="fzf --height 100% --reverse"

ZSH_THEME="powerlevel10k/powerlevel10k"

ZLE_RPROMPT_INDENT=0

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=$HOME'/.zsh_history'

# TERM=xterm-256color
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION

# NPM packages
NPM_PACKAGES="${HOME}/.npm/packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# PIP packages
export PATH="$PATH:$HOME/.local/bin"

# Rust Cargo binaries
export PATH="$PATH:$HOME/.cargo/bin"

# export MANPAGER="vim -M +MANPAGER -"

# Vim settings
# bindkey -v

# PAGER="nvim"
VISUAL="nvim"
EDITOR="nvim"

# ZStyle settings
# default fzf settings to apply globally
FZF_TAB_DEFAULT_FZF_FLAGS=(
  "--height=95%"
  "--multi"
  "--no-exact"
)
FZF_DEFAULT_OPTS="-i"
zstyle ":fzf-tab:*" fzf-flags "${FZF_TAB_DEFAULT_FZF_FLAGS[@]}"

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:git-reset:*' sort false

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no

# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'

# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

# show systemd unit status
zstyle ':fzf-tab:complete:systemctl-*:*' fzf-preview 'SYSTEMD_COLORS=1 systemctl status $word'

# tldr
zstyle ':fzf-tab:complete:tldr:argument-1' fzf-preview 'tldr --color always $word'

# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-preview \
  '[[ $group == "[process ID]" ]] && ps --pid=$word -o cmd --no-headers -w -w'
zstyle ':fzf-tab:complete:(kill|ps):argument-rest' fzf-flags --preview-window=down:3:wrap

# exa settings
export EXA_ICON_SPACING=2
source $HOME/.config/zsh/lscolors.sh

# Forgit options
export FORGIT_FZF_DEFAULT_OPTS="
--cycle
--reverse
--exact
--height '96%'
"

# Atuin settings
export ATUIN_NOBIND="true"
eval "$(atuin init zsh)"

# depends on terminal mode
bindkey '^r' atuin-search
bindkey '^[[A' atuin-up-search
bindkey '^[OA' atuin-up-search

# BAT
export BAT_THEME="gruvbox-dark"

# Pacman TUI function
# credits to https://github.com/IBArbitrary/dotfiles/blob/master/.config/fish/config.fish#L72-L78
# Search packages with 'fzf'
function pacs {
    pacman -Slq | fzf --prompt 'pacman> ' \
        --header 'Install packages.
        <c-p>: pacman, <c-a>: aur' \
        --bind 'ctrl-p:change-prompt(pacman> )+reload(pacman -Slq)' \
        --bind 'ctrl-a:change-prompt(aur> )+reload(yay -Slq)' \
        --multi --height=100% --preview 'yay -Si {1}' \
        --preview-window=right,65% --layout=reverse | xargs -ro yay -S
    pacman -Qqe >~/.config/pac-kages.txt
}

# Search and remove locally installed packages with 'fzf'
function pacr {
    pacman -Qq | fzf --prompt 'all> ' \
        --header='Remove packages.
        <c-a>: all, <c-e>: explicit, <c-y>: aur-explicit' \
        --bind 'ctrl-a:change-prompt(all> )+reload(pacman -Qq)' \
        --bind 'ctrl-e:change-prompt(exp> )+reload(pacman -Qe)' \
        --bind 'ctrl-y:change-prompt(aur> )+reload(pacman -Qm)' \
        --multi --height=100% --preview 'yay -Si {1}' \
        --preview-window=right,65% --layout=reverse | xargs -ro sudo pacman -Rsn
    pacman -Qqe >~/.config/packages.txt
}

# Aliases
alias vi=nvim
# alias vim=nvim
alias vv="nvim --listen /tmp/nvimsocket"
alias vvl="nvim --listen /tmp/nvimsocket -u $HOME/.config/nvim/init-light.lua"
alias v="nvim"
alias vl="nvim -u $HOME/.config/nvim/init-light.lua"

alias ..='cd ..'
alias ...='cd ../..'
alias l="exa --icons -lh --git --sort=type --time-style=long-iso --color=always"
alias ll="exa --icons -lah --git --sort=type --time-style=long-iso --color=always"
alias ls="exa --icons --git --color=always"
alias rm="rm -i"
alias dl="cd ~/Downloads"
alias co="cd ~/Code"
alias rip='yt-dlp -f "bv*[height<=1080]+ba/b[height<=1080] / wv*+ba/w"'
alias ripau="yt-dlp --progress --verbose --extract-audio --audio-format mp3"
alias doom="~/.emacs.d/bin/doom"
alias comp="setsid plasmashell --replace"
alias gs='git status --column'
alias gsm="git status --short | grep '^\s.'"
alias gsu="git status --short | grep '^??'"
alias gss="git status --short | grep '^[MARCD]'"
alias gcm="git commit -m"
alias fxzip='zip -r ~/Downloads/firefox.zip ~/.mozilla'
alias pipup='pip freeze --user | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install --user -U'
alias upd='zplug update && omz update'
alias matrix="cmatrix -b -u 8 -C cyan"
alias colors='~/Git/dotfiles/scripts/colors/showcolors'
alias st="speedtest --no-upload --single"
alias bup="sh ~/Dropbox/scripts/backup.sh"
alias grep='grep --color=auto'
# alias v="~/.config/vifm/scripts/vifmrun ."

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
