# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

source ~/.zplug/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/pass", from:oh-my-zsh
zplug "zplug/zplug", hook-build:'zplug --self-manage'
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zpm-zsh/ls"
zplug "b4b4r07/enhancd", use:init.sh
zplug "MichaelAquilina/zsh-auto-notify"
zplug "junegunn/fzf"
zplug "clvv/fasd"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "ellie/atuin"                                       # shell history
# zplug "rupa/z", use:z.sh                                  # jump around
# zplug "changyuheng/fz", defer:1
# zplug "jeffreytse/zsh-vi-mode"

if ! zplug check; then
    zplug install
fi

zplug load

if zplug check b4b4r07/enhancd; then
    # setting if enhancd is available
    export ENHANCD_FILTER=fzf-tmux
fi

source ~/.zplug/repos/b4b4r07/enhancd/init.sh

ENHANCD_DIR=$HOME/.zplug/repos/b4b4r07/enhancd/

ZSH_THEME="powerlevel10k/powerlevel10k"

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=$HOME'/.zsh_history'

# TERM=xterm-256color
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION

# NPM packages

NPM_PACKAGES="${HOME}/.npm/packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# PIP packages

export PATH="$PATH:$HOME/.local/bin"

# export MANPAGER="vim -M +MANPAGER -"

# Vim settings

bindkey -v
# bindkey '^r' history-incremental-search-backward

# PAGER="nvim"
VISUAL="nvim"
EDITOR="nvim"

ZVM_VI_HIGHLIGHT_BACKGROUND=#504945

# Atuin settings

export ATUIN_NOBIND="true"
eval "$(atuin init zsh)"

bindkey '^r' _atuin_search_widget

# depends on terminal mode
bindkey '^[[A' _atuin_search_widget
bindkey '^[OA' _atuin_search_widget

# fasd settings
eval "$(fasd --init auto)"

alias vi=nvim
alias vim=nvim

alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
alias l="exa --icons -l"
alias la="exa --icons -la"
alias ll="exa --icons -ll"
alias rm="rm -i"
alias weather="curl wttr.in/Preston"
alias dl="cd ~/Downloads"
alias rip="yt-dlp"
alias ripau="yt-dlp --progress --verbose --extract-audio --audio-format mp3"
alias blmake='make update && rm -rfv ~/Data/Blender/build_linux/bin/*.* && make ccache'
alias bldir="~/Data/Blender/blender"
alias bl="~/Data/Blender/build_linux/bin/blender"
alias doom="~/.emacs.d/bin/doom"
alias comp="setsid plasmashell --replace"
alias gs='git status --column'
alias gsm="git status --short | grep '^\s.'"
alias gsu="git status --short | grep '^??'"
alias gss="git status --short | grep '^[MARCD]'"
alias fxzip='zip -r ~/Dropbox/firefox.zip ~/.mozilla'
alias pipup='pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'
alias upd='omz update && zplug update && doom upgrade'
alias matrix="cmatrix -b -u 8 -C cyan"
alias colors='~/.scripts/colors/showcolors'
alias v="~/.config/vifm/scripts/vifmrun ."
alias st="speedtest --no-upload --single"

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
