# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

source ~/.zplug/init.zsh

zplug "plugins/git",   from:oh-my-zsh
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug 'zsh-users/zsh-autosuggestions'
zplug 'zsh-users/zsh-completions'
zplug 'supercrabtree/k'
zplug "zpm-zsh/ls"
zplug "b4b4r07/enhancd", use:init.sh
zplug 'MichaelAquilina/zsh-auto-notify'
zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh                                  # jump around
# zplug "jeffreytse/zsh-vi-mode"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

if ! zplug check; then
    zplug install
fi

zplug load

if zplug check b4b4r07/enhancd; then
    # setting if enhancd is available
    export ENHANCD_FILTER=fzf-tmux
fi

source ~/.zplug/repos/b4b4r07/enhancd/init.sh

ENHANCD_DIR=$HOME/.zplug/repos/b4b4r07/enhancd/

ZSH_THEME="powerlevel10k/powerlevel10k"

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=$HOME'/.zsh_history'

# TERM=xterm-256color
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION

# NPM packages

NPM_PACKAGES="${HOME}/.npm/packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"


# Vim settings

bindkey -v

PAGER="nvim"
VISUAL="nvim"
EDITOR="nvim"

ZVM_VI_HIGHLIGHT_BACKGROUND=#504945

alias vi=nvim
alias vim=nvim

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
alias cls='clear'
alias s='sudo'
alias l="ls -la"
alias la="ls -AF ${colorflag}"
alias ll="ls -lFh ${colorflag}"
alias lld="ls -l | grep ^d"
alias rm="rm -i"
alias weather="curl wttr.in/Preston"
alias dl="cd ~/Downloads"
alias rip="yt-dlp"
alias ripau="yt-dlp --extract-audio --audio-format mp3"
alias blmake='make update && rm -rfv ~/Blender/build_linux/bin/*.* && make ccache'
alias bldir="~/Blender/blender"
alias bl="~/Blender/build_linux/bin/blender"
alias doom="~/.emacs.d/bin/doom"
alias comp="setsid plasmashell --replace"
alias gs='git status'
alias fxzip='zip -r ~/Dropbox/firefox.zip ~/.mozilla'
alias pipup='pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'
alias upd='omz update && zplug update && doom upgrade'
alias matrix="cmatrix -b -u 8 -C cyan"
alias colors='~/.scripts/colors/showcolors'
alias v="~/.config/vifm/scripts/vifmrun ."

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
